bitbucket:
  base_url: 'https://bitbucket.ase.in.tum.de'

artemis:
  base_url: 'https://artemis.ase.in.tum.de/api'

  credentials:
    username: 'ge42abc'
    password: ''

  course:
    id: 37
    name: 'pgdp1920'

general:
  fix_eclipse_import: True
